version: "3"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - express-api

  express-api:
    hostname: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - express-api



networks:
  default:
    driver: bridge
