version: "3"
services:
  react-app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - express-api
      - express-api-2

  express-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3001
    expose:
      - "3001"

  express-api-2:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - PORT=3002
    expose:
      - "3002"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - express-api
      - express-api-2
